sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_script:
- pip install docker-compose
- docker-compose build
- docker-compose create db
- docker-compose start db
- sleep 20
- docker exec truecostofcoal_db_1 createdb -U postgres ttt;psql -U postgres -d ttt -c "CREATE EXTENSION postgis;"
- docker-compose run web python manage.py makemigrations 
- docker-compose run web python manage.py migrate


script:
- docker ps
- docker-compose run web python manage.py test
