sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_script:
- pip install docker-compose
- docker-compose build
- docker-compose create db
- docker-compose start db
- sleep 20



script:
- docker ps
- docker-compose run web python manage.py test
