sudo: required
language: python
addons: 
  ssh_known_hosts: git.divio.com
python:
- '3.6'
services:
- docker
before_script:
- pip install docker-compose
- docker-compose build
- docker-compose create db
- docker-compose start db
- sleep 10
- docker exec truecostofcoal_db_1 createdb -U postgres db
- sleep 2
- docker exec truecostofcoal_db_1 psql -U postgres -d db -c "CREATE EXTENSION postgis;"
- docker-compose run web python manage.py makemigrations
- docker-compose run web python manage.py migrate
script:
- docker ps
- docker-compose run web python manage.py test

after_success:
  - |

       $(npm bin)/set-up-ssh --key "$encrypted_1977bc1ec2e9_key" \
                             --iv "$encrypted_1977bc1ec2e9_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
  - git remote add divio git@git.divio.com:truecostofcoal.git
  - git push divio $TRAVIS_BRANCH
