# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 00:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import nece.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('story', models.TextField(verbose_name='The hole Story')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('region', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('min_zoom', models.IntegerField(verbose_name='Minimal zoom')),
            ],
            bases=(models.Model, nece.managers.TranslationMixin),
        ),
    ]
